### ISSUE TITLE
No Sound with Presence of the Footstep

### ISSUE THREAD

**Issue by ardissaps** [gamma1772/AdditionalBarsFabric#10]
**Reproduction**
- Install [PresenceOfTheFoodstep](https://modrinth.com/mod/presence-footsteps).
- Build any **Metal Bar** from [AdditionalsBarsFabric](https://modrinth.com/mod/additionalbars) (Wood Variant Produce Sound).
- Get foot on top of any block from the mod.

**Expected behavior**
 - Produce sound when foot step there, maybe could add material tag or something there?

**System information:**
 - OS: Windows 11
 - Java version Adoptium Temurin Latest 17
 - MC Version 1.18.2
 - Mod version 3.1.0 (Latest)

**Additional context**
Every Metal bar does not have sound vertical and horizontal.
![image](https://user-images.githubusercontent.com/82106625/175979529-330c8dce-e962-4944-a581-00b7a3300429.png)
All vanilla and most modded blocks and item do produce sound with mentioned mods.
I hope it can be fixed as your bar is the best! Thank you very much!

**Comment by ardissaps** [comment]
Is it mean it will get fix ported to 1.18.2?

**Comment by gamma1772** [comment]
Yes

**Comment by ardissaps** [comment]
Thank you very much!

**Comment by gamma1772** [comment]
No problem, 3.1.1 fix has just been uploaded to [Modrinth](https://modrinth.com/mod/additionalbars/version/3.1.1), [CurseForge](https://www.curseforge.com/minecraft/mc-mods/additional-bars-fabric) and [GitHub Releases](https://github.com/gamma1772/AdditionalBarsFabric/releases/tag/3.1.1), for both 1.18.2 and 1.19.
