### ISSUE TITLE
Would you please fix the Z fighting for the Classic Model?

### ISSUE THREAD

**Issue by ardissaps** [gamma1772/AdditionalBarsFabric#12]
As comparison with the [VanillaTweaks](https://vanillatweaks.net/picker/resource-packs/) iron bars on the right :
![image](https://user-images.githubusercontent.com/82106625/176394949-3fff41ba-a571-49e2-9167-38c3ba8ef6f4.png)
Same happen with the horizontal bars :
![image](https://user-images.githubusercontent.com/82106625/176396488-aa62ccf7-b81e-49be-a137-668e10f91e4b.png)
You can use [VanillaTweaks](https://vanillatweaks.net/picker/resource-packs/) (in the bottom Category of the website) fix bar as reference.
Honestly I like your classic model than the 3D one but it have Z fight as screenshot (i found the file in on your jar!).
Maybe you can add config option to choose between 3D and 2D in the config menu?
Thank you very much! (1.18.2)

**Comment by gamma1772** [comment]
I've published 3.2.0 on GitHub Releases, can you check if the z-flight still persists?
[Additional Bars 3.2.0](https://github.com/gamma1772/AdditionalBarsFabric/releases/tag/3.2.0)

**Comment by ardissaps** [comment]
@gamma1772 it is now vertical fixed but somewhat make the horizontal have Z-fight instead :
![image](https://user-images.githubusercontent.com/82106625/176703839-9ef98089-afbd-45e3-9baa-182198be0c32.png)

**Comment by gamma1772** [comment]
Uploaded 3.3.1 to GitHub releases, should fix this and #13

**Comment by ardissaps** [comment]
> Uploaded 3.3.1 to GitHub releases, should fix this and #13
Work perfectly now, thank you!
![image](https://user-images.githubusercontent.com/82106625/176730535-1fcad542-46af-44ba-8b6a-1d12fad047ee.png)

**Comment by gamma1772** [comment]
Awesome!
